version: '3'

services:
    nginx:
        container_name: phpmyadmin-nginx
        image: 00zi/nginx:latest
        restart: always
        volumes:
            - phpmyadmin:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 80
        labels:
            - "SERVICE_NAME=phpmyadmin-service"
        networks:
            shared_net:
        depends_on:
            - builder
    php:
        container_name: phpmyadmin-php
        image: 00zi/php7.1
        restart: always
        volumes:
            - phpmyadmin:/var/www/html
        networks:
            shared_net:
        depends_on:
            - builder
    builder:
        build: .
        container_name: phpmyadmin-builder
        volumes:
            - phpmyadmin:/var/www/html
        networks:
            shared_net:
        environment:
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - PMA_USER=${PMA_USER}
            - PMA_PASSWORD=${PMA_PASSWORD}
            - HOST=${HOST}

volumes:
    phpmyadmin:

networks:
    shared_net:
        external:
            name: shared_net
