version: '3'

services:
    mariadb:
        image: mariadb
        container_name: mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql-date:/var/lib/mysql
        networks:
            shared_net:
                ipv4_address: 172.30.0.33
        ports:
            - '3306:3306'
        labels:
            - "SERVICE_NAME=db-mariadb"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - 8080:80
        volumes:
            - /sessions
        external_links:
            - mariadb:db
        networks:
            shared_net:
                ipv4_address: 172.30.0.34

volumes:
    mysql-date:

networks:
    shared_net:
        external:
            name: shared_net
