version: '3'

services:
    haproxy:
        image: 00zi/haproxy
        container_name: haproxy
        restart: always
        ports:
            - "80:80"
        networks:
            - php5.2-net
            - php5.3-net
            - php5.4-net
            - php5.5-net
            - php5.6-net
            - php7.0-net
            - php7.1-net
        volumes:
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        depends_on:
            - registrator

    consul:
        image: consul
        container_name: consul-php-farm
        restart: always
        command: consul agent
            -server
            -data-dir=/consul/data
            -advertise 172.1.0.101
            -ui
            -client 172.1.0.101
            -bootstrap
        networks:
            php5.2-net:
                ipv4_address: 172.1.0.101
        environment:
            CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
        volumes:
            - consul-php-farm-date:/consul

    registrator:
        image: gliderlabs/registrator
        container_name: registrator-php-farm
        restart: always
        command: consul://consul:8500
        depends_on:
            - consul
        networks:
            - php5.2-net
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        # volumes:
        #     - /home/zi/project/www:/var/www/html
        #     - /home/zi/project/www/logs/nginx/:/var/log/nginx
        #     - /home/zi/project:/mnt
        ports:
            - 80
        networks:
            php5.2-net:
                ipv4_address: 172.1.0.10
            php5.3-net:
                ipv4_address: 172.1.1.10
            php5.4-net:
                ipv4_address: 172.1.2.10
            php5.5-net:
                ipv4_address: 172.1.3.10
            php5.6-net:
                ipv4_address: 172.1.4.10
            php7.0-net:
                ipv4_address: 172.1.5.10
            php7.1-net:
                ipv4_address: 172.1.6.10
        # links:
        #     - haproxy
        depends_on:
            - registrator

    php5-2:
        image: 00zi/php5.2
        container_name: php5-2
        restart: always
        volumes:
            - /home/zi/project/www:/var/www/html
            - /home/zi/project:/mnt
        ports:
            - 9000
        networks:
            php5.2-net:
                ipv4_address: 172.1.0.52
        labels:
            - "SERVICE_NAME=php5-2"
        depends_on:
            - registrator

    php5-3:
        image: 00zi/php5.3
        container_name: php5-3
        restart: always
        volumes:
            - /home/zi/project/www:/var/www/html
            - /home/zi/project:/mnt
        ports:
            - 9000
        networks:
            php5.3-net:
                ipv4_address: 172.1.1.53
        labels:
            - "SERVICE_NAME=php5-3"
        depends_on:
            - registrator

    php5-4:
        image: 00zi/php5.4
        container_name: php5-4
        restart: always
        volumes:
            - /home/zi/project/www:/var/www/html
            - /home/zi/project:/mnt
        ports:
            - 9000
        networks:
            php5.4-net:
                ipv4_address: 172.1.2.54
        labels:
            - "SERVICE_NAME=php5-4"
        depends_on:
            - registrator

    php5-5:
        image: 00zi/php5.5
        container_name: php5-5
        restart: always
        volumes:
            - /home/zi/project/www:/var/www/html
            - /home/zi/project:/mnt
        ports:
            - 9000
        networks:
            php5.5-net:
                ipv4_address: 172.1.3.55
        labels:
            - "SERVICE_NAME=php5-5"
        depends_on:
            - registrator

    php5-6:
        image: 00zi/php5.6
        container_name: php5-6
        restart: always
        volumes:
            - /home/zi/project/www:/var/www/html
            - /home/zi/project:/mnt
        ports:
            - 9000
        networks:
            php5.6-net:
                ipv4_address: 172.1.4.56
        labels:
            - "SERVICE_NAME=php5-6"
        depends_on:
            - registrator

    php7-0:
        image: 00zi/php7.0
        container_name: php7-0
        restart: always
        volumes:
            - /home/zi/project/www:/var/www/html
            - /home/zi/project:/mnt
        ports:
            - 9000
        networks:
            php7.0-net:
                ipv4_address: 172.1.5.70
        labels:
            - "SERVICE_NAME=php7-0"
        depends_on:
            - registrator

    php7-1:
        image: 00zi/php7.1
        container_name: php7-1
        restart: always
        volumes:
            - /home/zi/project/www:/var/www/html
            - /home/zi/project:/mnt
        ports:
            - 9000
        networks:
            php7.1-net:
                ipv4_address: 172.1.6.71
        labels:
            - "SERVICE_NAME=php7-1"
        depends_on:
            - registrator

    mariadb:
        image: 00zi/mariadb
        container_name: mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql-date:/var/lib/mysql
        networks:
            - php5.2-net
        ports:
            - '3306:3306'
        depends_on:
            - registrator

volumes:
    mysql-date:
    consul-php-farm-date:


networks:
    php5.2-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.1.0.0/24
    php5.3-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.1.1.0/24
    php5.4-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.1.2.0/24
    php5.5-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.1.3.0/24
    php5.6-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.1.4.0/24
    php7.0-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.1.5.0/24
    php7.1-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.1.6.0/24

