version: '3'

services:
    haproxy:
        build: ./haproxy
        restart: always
        ports:
            - 80
        container_name: haproxy-farm
        networks:
            shared_net:
                ipv4_address: 172.30.0.80
            php5.2-net:
            php5.3-net:
            php5.4-net:
            php5.5-net:
            php5.6-net:
            php7.0-net:
            php7.1-net:
        labels:
            - "SERVICE_NAME=haproxy-farm"
            - "io.github.tehzi.service-ip=172.30.0.80"
        depends_on:
            - registrator

    consul:
        image: consul
        container_name: consul-php-farm
        restart: always
        command: consul agent
            -server
            -data-dir=/consul/data
            -advertise 172.16.0.101
            -ui
            -client 172.16.0.101
            -bootstrap
        networks:
            php5.2-net:
                ipv4_address: 172.16.0.101
        environment:
            CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
        volumes:
            - consul-php-farm-date:/consul

    registrator:
        image: gliderlabs/registrator:master
        container_name: registrator-php-farm
        restart: always
        command: -useIpFromLabel=io.github.tehzi.service-ip consul://consul:8500
        depends_on:
            - consul
        networks:
            - php5.2-net
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - 80
        volumes:
            - ${WWW_DIR}:/var/www/html
            - ${PROJECT_DIR}:/mnt
        networks:
            php5.2-net:
                ipv4_address: 172.16.0.10
            php5.3-net:
                ipv4_address: 172.16.1.10
            php5.4-net:
                ipv4_address: 172.16.2.10
            php5.5-net:
                ipv4_address: 172.16.3.10
            php5.6-net:
                ipv4_address: 172.16.4.10
            php7.0-net:
                ipv4_address: 172.16.5.10
            php7.1-net:
                ipv4_address: 172.16.6.10
        depends_on:
            - registrator

    php5-2:
        image: 00zi/php5.2
        container_name: php5-2
        restart: always
        volumes:
            - ${WWW_DIR}:/var/www/html
            - ${PROJECT_DIR}:/mnt
        ports:
            - 9000
        networks:
            php5.2-net:
                ipv4_address: 172.16.0.52
        labels:
            - "SERVICE_NAME=php5-2"
        depends_on:
            - registrator

    php5-3:
        image: 00zi/php5.3
        container_name: php5-3
        restart: always
        volumes:
            - ${WWW_DIR}:/var/www/html
            - ${PROJECT_DIR}:/mnt
        ports:
            - 9000
        networks:
            php5.3-net:
                ipv4_address: 172.16.1.53
        labels:
            - "SERVICE_NAME=php5-3"
        depends_on:
            - registrator

    php5-4:
        image: 00zi/php5.4
        container_name: php5-4
        restart: always
        volumes:
            - ${WWW_DIR}:/var/www/html
            - ${PROJECT_DIR}:/mnt
        ports:
            - 9000
        networks:
            php5.4-net:
                ipv4_address: 172.16.2.54
        labels:
            - "SERVICE_NAME=php5-4"
        depends_on:
            - registrator

    php5-5:
        image: 00zi/php5.5
        container_name: php5-5
        restart: always
        volumes:
            - ${WWW_DIR}:/var/www/html
            - ${PROJECT_DIR}:/mnt
        ports:
            - 9000
        networks:
            php5.5-net:
                ipv4_address: 172.16.3.55
        labels:
            - "SERVICE_NAME=php5-5"
        depends_on:
            - registrator

    php5-6:
        image: 00zi/php5.6
        container_name: php5-6
        restart: always
        volumes:
            - ${WWW_DIR}:/var/www/html
            - ${PROJECT_DIR}:/mnt
        ports:
            - 9000
        networks:
            php5.6-net:
                ipv4_address: 172.16.4.56
        labels:
            - "SERVICE_NAME=php5-6"
        depends_on:
            - registrator

    php7-0:
        image: 00zi/php7.0
        container_name: php7-0
        restart: always
        volumes:
            - ${WWW_DIR}:/var/www/html
            - ${PROJECT_DIR}:/mnt
        ports:
            - 9000
        networks:
            php7.0-net:
                ipv4_address: 172.16.5.70
        labels:
            - "SERVICE_NAME=php7-0"
        depends_on:
            - registrator

    php7-1:
        image: 00zi/php7.1
        container_name: php7-1
        restart: always
        volumes:
            - ${WWW_DIR}:/var/www/html
            - ${PROJECT_DIR}:/mnt
        ports:
            - 9000
        networks:
            php7.1-net:
                ipv4_address: 172.16.6.71
        labels:
            - "SERVICE_NAME=php7-1"
        depends_on:
            - registrator

volumes:
    mysql-date:
    consul-php-farm-date:

networks:
    php5.2-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.0.0/24
    php5.3-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.1.0/24
    php5.4-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.2.0/24
    php5.5-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.3.0/24
    php5.6-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.4.0/24
    php7.0-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.5.0/24
    php7.1-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.6.0/24
    shared_net:
            external:
                name: shared_net
